DBCC SHRINKFILE (tempdb01, 2);
GO
DBCC SHRINKFILE (tempdb02, 2);
GO
DBCC SHRINKFILE (tempdb03, 2);
GO
DBCC SHRINKFILE (tempdb04, 2);
GO
DBCC SHRINKFILE (tempdb05, 2);
GO
DBCC SHRINKFILE (tempdb06, 2);
GO
DBCC SHRINKFILE (tempdb07, 2);
GO
DBCC SHRINKFILE (tempdb08, 2);
GO
DBCC SHRINKFILE (tempdb09, 2);
GO
DBCC SHRINKFILE (tempdb10, 2);
GO
DBCC SHRINKFILE (tempdb11, 2);
GO
DBCC SHRINKFILE (tempdb12, 2);
GO
DBCC SHRINKFILE (tempdb13, 2);
GO
DBCC SHRINKFILE (tempdb14, 2);
GO
DBCC SHRINKFILE (tempdb15_disk_e, 2);
GO